-- Basic config
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')

-- Plugins config
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.mason')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.null-ls')
require('plugins.telescope')
require('plugins.autopairs')
require('plugins.comments')
require('plugins.toggleterm')
require('plugins.outline')
require('plugins.lualine')
require('plugins.bufferline')
require('plugins.gitsigns')
require('plugins.autosession')
require('plugins.diffview')
